server:
  port: 8096

spring:
  application:
    name: vg-ms-attendance
  data:
    mongodb:
      uri: mongodb+srv://gabrielgutierrezq:3mbmCx8Gx6hrRKHY@as221s5prs2.1e7z9.mongodb.net/AS221S5PRS2?retryWrites=true&w=majority&appName=AS221S5PRS2

# Microservice health meter
management:
  endpoint:
    health:
      show-details: always

# Endpoint de actuator
api:
  version: api/v1

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/attendance

# Servicios externos
services:
  classroom:
    url: ${CLASSROOM_SERVICE_URL:https://vg-ms-classroom-production-37bc.up.railway.app/management/api/v1/classroom/list/active}
  institucional-staff:
    url: ${INSTITUCIONAL_STAFF_SERVICE_URL:https://vg-ms-institucional-staff-production.up.railway.app/management/api/v1/institucional-staff/list/active}
